### ISSUE TITLE
CI: Test PRs using CI

### ISSUE THREAD

**Issue by JakobMiksch** [klips-project/klips-sdi#42]
The CI should test PRs like it is done it https://github.com/klips-project/rabbitmq-worker

**Comment by weskamm** [comment]
what exactly do you want to be tested? workers? api? linting?

**Comment by JakobMiksch** [comment]
good question :sweat_smile: 
this repo actually contains many sub-projects and parts that would need individual tests or linting. 
We are still in a developing phase where much is changing, but ideally there would be some tests to ensure the proper functionality of everything.
we can leave this issue as reminder.

**Comment by JakobMiksch** [comment]
closing because not relevant currently
